In [2]:
from tensorflow.keras.preprocessing.text import one_hot

d:\Kunal_Learning_ML\Learning-ML\venv\lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
d:\Kunal_Learning_ML\Learning-ML\venv\lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
d:\Kunal_Learning_ML\Learning-ML\venv\lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resource_handle.proto. Please update the gencode

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9815, 3831, 5444, 4736],
 [9815, 3831, 5444, 4116],
 [9815, 6701, 5444, 4454],
 [3947, 9100, 8090, 2767, 3738],
 [3947, 9100, 8090, 2767, 1344],
 [3025, 9815, 2867, 5444, 8726],
 [9929, 4658, 6133, 2767]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9815 3831 5444 4736]
 [   0    0    0    0 9815 3831 5444 4116]
 [   0    0    0    0 9815 6701 5444 4454]
 [   0    0    0 3947 9100 8090 2767 3738]
 [   0    0    0 3947 9100 8090 2767 1344]
 [   0    0    0 3025 9815 2867 5444 8726]
 [   0    0    0    0 9929 4658 6133 2767]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Kunal_Learning_ML\Learning-ML\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step


array([[[-0.02648844,  0.033304  ,  0.04289557,  0.04913595,
          0.04584234,  0.03105979,  0.04255731, -0.02937716,
         -0.00123964,  0.0343117 ],
        [-0.02648844,  0.033304  ,  0.04289557,  0.04913595,
          0.04584234,  0.03105979,  0.04255731, -0.02937716,
         -0.00123964,  0.0343117 ],
        [-0.02648844,  0.033304  ,  0.04289557,  0.04913595,
          0.04584234,  0.03105979,  0.04255731, -0.02937716,
         -0.00123964,  0.0343117 ],
        [-0.02648844,  0.033304  ,  0.04289557,  0.04913595,
          0.04584234,  0.03105979,  0.04255731, -0.02937716,
         -0.00123964,  0.0343117 ],
        [ 0.02034397, -0.04966734, -0.00413867,  0.04425091,
         -0.00245595, -0.02602954,  0.01105688, -0.03048236,
          0.03902951, -0.03843134],
        [ 0.01188754, -0.00033306, -0.01938471,  0.0041513 ,
         -0.02906817,  0.02128137,  0.03706212,  0.0485731 ,
         -0.03965062, -0.04029676],
        [ 0.03200719, -0.02213718, -0.0376776 , -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9815, 3831, 5444, 4736], dtype=int32)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>