In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
X,y = load_iris(return_X_y=True)

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [6]:
##use gaussian as all independent features are continuous
from sklearn.naive_bayes import GaussianNB

In [7]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)

,priors,None
,var_smoothing,1e-09


In [8]:
y_pred = gnb.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [10]:
import seaborn as sns
df = sns.load_dataset('tips')

In [11]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [15]:
df['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [16]:
# we will try to predict smoker or not using gnb
#first convert the text and all into numerical values
df['sex'] = df['sex'].apply(lambda x : 1 if x == 'Male' else 0)

In [18]:
df['sex'].value_counts()

sex
1    157
0     87
Name: count, dtype: int64

In [21]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [22]:
df['day'] = df['day'].map({'Sat' : 0, 'Sun' : 1, 'Thur' : 2, 'Fri' : 3})

In [23]:
df['day'].value_counts()

day
0    87
1    76
2    62
3    19
Name: count, dtype: int64

In [24]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,0,No,1,Dinner,2
1,10.34,1.66,1,No,1,Dinner,3
2,21.01,3.50,1,No,1,Dinner,3
3,23.68,3.31,1,No,1,Dinner,2
4,24.59,3.61,0,No,1,Dinner,4


In [25]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [26]:
df['time'] = df['time'].apply(lambda x : 1 if x == 'Dinner' else 0)

In [28]:
df['time'].value_counts()

time
1    176
0     68
Name: count, dtype: int64

In [30]:
df['smoker'] = df['smoker'].apply(lambda x : 1 if x == 'Yes' else 0)

In [31]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,0,0,1,1,2
1,10.34,1.66,1,0,1,1,3
2,21.01,3.50,1,0,1,1,3
3,23.68,3.31,1,0,1,1,2
4,24.59,3.61,0,0,1,1,4


In [46]:
y.isna().sum()

np.int64(0)

In [53]:
X = df.drop(columns=['smoker'])
y = df['smoker']
X = X.reset_index(drop=True)
y = y.reset_index(drop=True)

In [54]:
X.shape,y.shape

((244, 6), (244,))

In [55]:
X_train,X_train,y_train,y_test = train_test_split(X,y)

In [56]:
gnb = GaussianNB()

In [57]:
gnb.fit(X_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [61, 183]