In [1]:
!pip install numpy

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)
arr.reshape(1,5)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


array([[1, 2, 3, 4, 5]])

In [8]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,23,2,3,4])
print(arr1+arr2)

[ 2 25  5  7  9]
